export const CHANGE_MENU = 'CHANGE_MENU';
export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const SELECT_TOPIC = 'SELECT_TOPIC';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const LOAD_TOPIC_LIST = 'LOAD_TOPIC_LIST';
export const LOAD_PROBLEM = 'LOAD_PROBLEM';
export const ADD_PROBLEM_RESULT = 'ADD_PROBLEM_RESULT';